### ISSUE TITLE
Farmers delight oven does not work with bread recipe

### ISSUE THREAD

**Issue by ericbv** [qwek1/All-of-Create#20]
Using AOC version 3.0

when trying use the following recipe with the farmers delight oven
![image](https://github.com/qwek1/All-of-Create/assets/2890834/8f7733bc-3c95-44f8-9f95-2e3cd13bbe47)

i get the following exception:
`[13:05:43] [Server thread/WARN] [neruina/]: Neruina Caught Exception
java.lang.NullPointerException: Cannot read field "f_19853_" because "p_41624_" is null
        at net.minecraft.world.item.ItemStack.m_41622_(ItemStack.java:352) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:recipeessentials.mixins.json:nbt.ItemStack                                                                Mixin,pl:mixin:APP:necronomicon.forge.mixins.json:AnimatedItemNameMixin,pl:mixin:APP:canary.mixins.json:item.ItemStackMixin,pl:mixin:APP:canary.mixins.json:util.item_stack_tracking.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:                                                                APP:extendedgears-common.mixins.json:MixinItemStack,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
        at com.lance5057.extradelight.workstations.oven.OvenBlockEntity.processCooking(OvenBlockEntity.java:331) ~[extradelight-1.3.jar%23375!/:1.3] {re:classloading}
        at com.lance5057.extradelight.workstations.oven.OvenBlockEntity.cookingTick(OvenBlockEntity.java:138) ~[extradelight-1.3.jar%23375!/:1.3] {re:classloading}
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.mixinextras$bridge$m_155252_$11(LevelChunk.java) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:                                                                mixin:APP:neruina-common.mixins.json:WorldChunkMixin$DirectBlockEntityTickInvokerMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.world_border.BoundTickingBlockEntityMixin,pl:mixin:A}
        at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickBlockEntity$notTheCauseOfTickLag(NeruinaTickHandler.java:96) ~[neruina-1.3.0-forge+1.18.2-1.20.1.jar%23425!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.wrapOperation$zna000$catchTickingBlockEntity(LevelChunk.java:811) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:access                                                                transformer:B,pl:mixin:APP:neruina-common.mixins.json:WorldChunkMixin$DirectBlockEntityTickInvokerMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.world_border.BoundTickingBlockEntityMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:neruina-                                                                common.mixins.json:WorldChunkMixin$DirectBlockEntityTickInvokerMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.world_border.BoundTickingBlockEntityMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:world.block_entity_tick                                                                ing.sleeping.RebindableTickingBlockEntityWrapperAccessor,pl:mixin:A}
        at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:mixin,pl:accesstransformer:B,x                                                                f:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,p                                                                l:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin,pl:mixin:APP:canary.mixins.json:util.block_entity_retrieval                                                                .LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json                                                                :world.inline_height.LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:neruina-common.mixins.json:WorldMixin,pl:mixin:APP:doespotatotick.mixins.json:WorldMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_                                                                pac_serverlevel_ispositionentityticking,xf:fml:xaeroworldmap:xaero_wm_serverlevel,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:                                                                fml:xaeroworldmap:xaero_wm_serverlevel,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modern                                                                fix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:neruina-common.mixins.json:ServerWorldMixin,pl:mixi                                                                n:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:idas.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.replace_streams.ServerLevelMixin,pl:mixin:                                                                APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.accessors.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.s                                                                leeping.ServerLevelMixin,pl:mixin:APP:ritchiesprojectilelib.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:simplerpc.mixins.json:ServerWorldMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl                                                                :mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_mi                                                                necraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixi                                                                n:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServe                                                                rMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransform                                                                er:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_mi                                                                necraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixi                                                                n:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServe                                                                rMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_                                                                minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mi                                                                xin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftSer                                                                verMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_                                                                minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mi                                                                xin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftSer                                                                verMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
`

**Comment by qwek1** [comment]
its an issue with the Extra Delight mod, updating it to the latest version should fix this issue
